src/WebUI/Models/ErrorViewModel.cs
namespace CosmeticSalon.WebUI.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(this.RequestId);
}

src/WebUI/Controllers/ApiController.cs
namespace CosmeticSalon.WebUI.Controllers;

using AutoMapper;

public class ApiController : Controller
{
    private IMapper? mapper;
    private ISender? mediator;
    protected IMapper Mapper => this.mapper ??= this.HttpContext.RequestServices.GetService<IMapper>()!;
    protected ISender Mediator => this.mediator ??= this.HttpContext.RequestServices.GetService<ISender>()!;
}

src/WebUI/Controllers/BaseController.cs
namespace CosmeticSalon.WebUI.Controllers;

using AutoMapper;

public class BaseController : Controller
{
    private IMapper? mapper;
    private ISender? mediator;
    protected IMapper Mapper => this.mapper ??= this.HttpContext.RequestServices.GetService<IMapper>()!;
    protected ISender Mediator => this.mediator ??= this.HttpContext.RequestServices.GetService<ISender>()!;
}

src/WebUI/Controllers/HomeController.cs
namespace CosmeticSalon.WebUI.Controllers;

using System.Diagnostics;
using CosmeticSalon.WebUI.Models;

public sealed class HomeController : BaseController
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return this.View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? this.HttpContext.TraceIdentifier });
    }

    public IActionResult Index()
    {
        return this.View();
    }

    public IActionResult Privacy()
    {
        return this.View();
    }
}

src/WebUI/Controllers/TreatmentsController.cs
namespace CosmeticSalon.WebUI.Controllers;

using CosmeticSalon.Application.Treatments.Commands;
using CosmeticSalon.Application.Treatments.Queries;
using CosmeticSalon.Application.Treatments.ViewModels;

[ApiController]
public sealed class TreatmentsController : BaseController
{
    private readonly ILogger<TreatmentsController> logger;

    public TreatmentsController(ILogger<TreatmentsController> logger)
    {
        this.logger = logger;
    }

    [Route("AddTreatment")]
    public IActionResult AddTreatmentView(CancellationToken cancellationToken = default)
    {
        return this.View();
    }

    [HttpPost, Route("AddTreatment"), ValidateAntiForgeryToken]
    public async Task<IActionResult> AddTreatmentView([FromForm] Treatment treatment, CancellationToken cancellationToken = default)
    {
        try
        {
            var id = Guid.NewGuid();

            treatment = treatment with { Id = id };

            var command = this.Mapper.Map<AddTreatment>(treatment);
            await this.Mediator.Send(command, cancellationToken);

            return await Task.FromResult(this.RedirectToAction(nameof(this.TreatmentsView)));
        }
        catch (Exception exception)
        {
            this.logger.LogError(exception, "{Message}", exception.Message);

            return await Task.FromResult(this.View());
        }
    }

    [HttpGet, Route("GetTreatments")]
    public async Task<IActionResult> TreatmentsView(CancellationToken cancellationToken = default)
    {
        var query = new GetTreatments();

        var treatments = await this.Mediator.Send(query, cancellationToken);

        return await Task.FromResult(this.View(treatments));
    }
}

src/WebUI/Controllers/UsersController.cs
namespace CosmeticSalon.WebUI.Controllers;

using CosmeticSalon.Application.Users.Commands;
using CosmeticSalon.Application.Users.Queries;
using CosmeticSalon.Application.Users.ViewModels;

[ApiController]
public sealed class UsersController : BaseController
{
    private readonly ILogger<UsersController> logger;

    public UsersController(ILogger<UsersController> logger)
    {
        this.logger = logger;
    }

    [Route("SignIn")]
    public IActionResult SignInView(CancellationToken cancellationToken = default)
    {
        return this.View();
    }

    [HttpPost, Route("SignIn"), ValidateAntiForgeryToken]
    public async Task<IActionResult> SignInView([FromForm] SignInUser user, CancellationToken cancellationToken = default)
    {
        if (this.ModelState.IsValid is false)
        {
            return this.View(user);
        }

        try
        {
            var command = this.Mapper.Map<SignIn>(user);
            await this.Mediator.Send(command, cancellationToken);

            return await Task.FromResult(this.RedirectToAction(nameof(this.UsersView)));
        }
        catch (Exception exception)
        {
            this.logger.LogError(exception, "{Message}", exception.Message);

            return await Task.FromResult(this.View());
        }
    }

    [Route("SignUp")]
    public IActionResult SignUpView(CancellationToken cancellationToken = default)
    {
        return this.View();
    }

    [HttpPost, Route("SignUp"), ValidateAntiForgeryToken]
    public async Task<IActionResult> SignUpView([FromForm] SignUpUser user, CancellationToken cancellationToken = default)
    {
        if (this.ModelState.IsValid is false)
        {
            return this.View(user);
        }

        try
        {
            var id = Guid.NewGuid();
            user = user with { Id = id };

            var command = this.Mapper.Map<SignUp>(user);
            await this.Mediator.Send(command, cancellationToken);

            return await Task.FromResult(this.RedirectToAction(nameof(this.UsersView)));
        }
        catch (Exception exception)
        {
            this.logger.LogError(exception, "{Message}", exception.Message);

            return await Task.FromResult(this.View());
        }
    }

    [HttpGet, Route("GetUsers")]
    public async Task<IActionResult> UsersView(CancellationToken cancellationToken = default)
    {
        var query = new GetUsers();

        var users = await this.Mediator.Send(query, cancellationToken);

        return await Task.FromResult(this.View(users));
    }
}

src/WebUI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

src/WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CosmeticSalon.WebUI</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CosmeticSalon.WebUI</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Treatments" asp-action="TreatmentsView">Treatments</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="UsersView">Users</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - CosmeticSalon.WebUI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

src/WebUI/Views/Treatments/AddTreatmentView.cshtml
@model CosmeticSalon.Application.Treatments.ViewModels.Treatment

<body>
<h1>
    Create Treatment
</h1>
<form asp-action="AddTreatmentView">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="Name" class="control-label"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Type" class="control-label"></label>
        <input asp-for="Type" class="form-control" />
        <span asp-validation-for="Type" class="text-danger"></span>
    </div>
    <div class="form-group">
        <input type="submit" value="Create" />
    </div>
</form>

</body>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

src/WebUI/Views/Treatments/TreatmentsView.cshtml
@model IReadOnlyList<CosmeticSalon.Application.Treatments.ViewModels.Treatment>

<body>

<h1>
    Treatments View
</h1>

@foreach (var treatment in Model)
{
    <div>
        @treatment.Id
    </div>
    <div>
        @treatment.Name
    </div>
    <div>
        @treatment.Type
    </div>

    @* foreach (var employee in treatment.Employees)
    {
        <div>
            @employee.Id
        </div>
        <div>
            @employee.Username
        </div>
    } *@
}
</body>

src/WebUI/Views/Users/SignInView.cshtml
@model CosmeticSalon.Application.Users.ViewModels.SignInUser
<body>
    <h1>
        Sign Up User
    </h1>
    <form asp-action="SignInView">
        <div class="form-group">
            <label asp-for="Username" class="control-label"></label>
                <input asp-for="Username" class="form-control" />
                <span asp-validation-for="Username" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Password" class="control-label"></label>
            <input asp-for="Password" class="form-control" />
            <span asp-validation-for="Password" class="text-danger"></span>
        </div>
        <div class="form-group">
            <input type="submit" value="Sign In" />
        </div>
    </form>
</body>

src/WebUI/Views/Users/SignUpView.cshtml
@model CosmeticSalon.Application.Users.ViewModels.SignUpUser

<body>
    <h1>
        Sign Up User
    </h1>
    <form asp-action="SignUpView">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Email" class="control-label"></label>
            <input asp-for="Email" class="form-control" />
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Username" class="control-label"></label>
            <input asp-for="Username" class="form-control" />
            <span asp-validation-for="Username" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Password" class="control-label"></label>
            <input asp-for="Password" class="form-control" />
            <span asp-validation-for="Password" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="ReapedPassword" class="control-label"></label>
            <input asp-for="ReapedPassword" class="form-control" />
            <span asp-validation-for="ReapedPassword" class="text-danger"></span>
        </div>
        <div class="form-group">
            <input type="submit" value="Sign Up" />
        </div>
    </form>

</body>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

src/WebUI/Views/Users/UsersView.cshtml
@model IReadOnlyList<CosmeticSalon.Application.Users.ViewModels.User>

<body>

<h1>
    Users View
</h1>

@foreach (var user in Model)
{
    <div>
        @user.Id
    </div>
    <div>
        @user.Username
    </div>
    <div>
        @user.Fullname
    </div>
    <div>
        @user.Role
    </div>
})
</body>